import type { MarketplaceProduct } from "@/components/marketplace/ProductCard";

export const dummyMarketplaceProducts: MarketplaceProduct[] = [
    {
        id: 1,
        name: "Fresh Maize (Grade 1)",
        description: "Sun-dried, well sorted maize. Moisture content below 13%. Ideal for milling or resale.",
        price: 4550,
        currency: "KES",
        quantity: "90kg bag",
        imageUrl: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc",
        category: "Grains",
        farmerName: "Peter Mwangi",
        farmerLocation: "Nakuru County",
        farmerPhone: "+254712345678",
        postedDate: "2026-02-20"
    },
    {
        id: 2,
        name: "Red Beans (Rosecoco)",
        description: "Clean, stone-free rosecoco beans harvested this season. High protein content.",
        price: 7800,
        currency: "KES",
        quantity: "90kg bag",
        imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c",
        category: "Legumes",
        farmerName: "Mary Achieng",
        farmerLocation: "Kisumu County",
        farmerPhone: "+254798765432",
        postedDate: "2026-02-22"
    },
    {
        id: 3,
        name: "Fresh Cassava Tubers",
        description: "Organic cassava, freshly harvested. Suitable for flour production or boiling.",
        price: 3500,
        currency: "KES",
        quantity: "100kg sack",
        imageUrl: "https://images.unsplash.com/photo-1592928302636-c83cf1e1e95b",
        category: "Root Crops",
        farmerName: "John Odhiambo",
        farmerLocation: "Siaya County",
        farmerPhone: "+254701234567",
        postedDate: "2026-02-23"
    },
    {
        id: 4,
        name: "Sorghum (Red Variety)",
        description: "Drought-resistant red sorghum. Cleaned and ready for milling.",
        price: 4200,
        currency: "KES",
        quantity: "90kg bag",
        imageUrl: "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea",
        category: "Grains",
        farmerName: "David Kiptoo",
        farmerLocation: "Uasin Gishu County",
        farmerPhone: "+254723456789",
        postedDate: "2026-02-18"
    },
    {
        id: 5,
        name: "Organic Kale (Sukuma Wiki)",
        description: "Fresh green sukuma wiki harvested daily. No chemical fertilizers used.",
        price: 800,
        currency: "KES",
        quantity: "50 bundles",
        imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5",
        category: "Vegetables",
        farmerName: "Agnes Wanjiru",
        farmerLocation: "Kiambu County",
        farmerPhone: "+254734567890",
        postedDate: "2026-02-24"
    },
    {
        id: 6,
        name: "Ripe Tomatoes (Grade A)",
        description: "Bright red, firm tomatoes suitable for market resale or processing.",
        price: 2500,
        currency: "KES",
        quantity: "60kg crate",
        imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea",
        category: "Vegetables",
        farmerName: "Samuel Mutua",
        farmerLocation: "Machakos County",
        farmerPhone: "+254745678901",
        postedDate: "2026-02-21"
    },
    {
        id: 7,
        name: "Fresh Avocados (Hass)",
        description: "Export-grade Hass avocados. Sorted by size and quality.",
        price: 6500,
        currency: "KES",
        quantity: "100 pieces",
        imageUrl: "https://images.unsplash.com/photo-1601039641847-7857b994d704",
        category: "Fruits",
        farmerName: "Grace Nyambura",
        farmerLocation: "Murang'a County",
        farmerPhone: "+254756789012",
        postedDate: "2026-02-19"
    },
    {
        id: 8,
        name: "Sweet Potatoes (Orange Flesh)",
        description: "Vitamin A rich sweet potatoes. Clean and freshly harvested.",
        price: 3800,
        currency: "KES",
        quantity: "100kg sack",
        imageUrl: "https://images.unsplash.com/photo-1598032895397-b9472444bf93",
        category: "Root Crops",
        farmerName: "Daniel Ochieng",
        farmerLocation: "Homa Bay County",
        farmerPhone: "+254767890123",
        postedDate: "2026-02-25"
    }
];